version: 2
registries:
  github:
    type: "maven-repository"
    url: "https://maven.pkg.github.com/pcalouche/*"
    username: ${{ github.actor }}
    password: ${{ github.token }}
updates:
  - package-ecosystem: "maven"
    directory: "/"
    registries: "*"
    schedule:
      interval: "daily"
    target-branch: "main"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "main"